version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-terrypassword}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-terry}
    volumes:
      - mongodb_data:/data/db
    networks:
      - terry_network

  # Backend service using buildpack pattern
  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/gizousa/terry-system-backend:latest}
    build:
      context: https://github.com/gizousa/terry-system.git#main
      dockerfile: backend/Dockerfile
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://${MONGO_USER:-terry_user}:${MONGO_PASSWORD:-terrypassword}@mongodb:27017/${MONGO_DATABASE:-terry}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DEEPINFRA_API_KEY=${DEEPINFRA_API_KEY:-}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-}
      - GROK_API_KEY=${GROK_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - DEFAULT_LLM_PROVIDER=${DEFAULT_LLM_PROVIDER:-openai}
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASS=${SMTP_PASS:-}
      - SMTP_FROM=${SMTP_FROM:-}
      - EVOLUTION_API_URL=${EVOLUTION_API_URL:-}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY:-}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL:-}
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY:-}
    networks:
      - terry_network

  # Frontend service using buildpack pattern
  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/gizousa/terry-system-frontend:latest}
    build:
      context: https://github.com/gizousa/terry-system.git#main
      dockerfile: frontend/Dockerfile
    restart: always
    depends_on:
      - backend
    networks:
      - terry_network

  # Nginx service for routing
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - terry_network

networks:
  terry_network:
    driver: bridge

volumes:
  mongodb_data:
